# TCL File Generated by Component Editor 18.1
# Tue Jun 09 02:46:10 CST 2026
# DO NOT MODIFY


# 
# volume_peakmeter "Volume & Peak Meter" v1.4
#  2026.06.09.02:46:10
# Control de volumen por encoder y medidor de pico de audio con visualización en LEDs
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module volume_peakmeter
# 
set_module_property DESCRIPTION "Control de volumen por encoder y medidor de pico de audio con visualización en LEDs"
set_module_property NAME volume_peakmeter
set_module_property VERSION 1.4
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Volume & Peak Meter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL volume_peakmeter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file volume_peakmeter.v VERILOG PATH ip/volume_peakmeter/volume_peakmeter.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DEBOUNCE_CYCLES INTEGER 100000
set_parameter_property DEBOUNCE_CYCLES DEFAULT_VALUE 100000
set_parameter_property DEBOUNCE_CYCLES DISPLAY_NAME DEBOUNCE_CYCLES
set_parameter_property DEBOUNCE_CYCLES TYPE INTEGER
set_parameter_property DEBOUNCE_CYCLES UNITS None
set_parameter_property DEBOUNCE_CYCLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEBOUNCE_CYCLES HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point external_signals
# 
add_interface external_signals conduit end
set_interface_property external_signals associatedClock clock
set_interface_property external_signals associatedReset ""
set_interface_property external_signals ENABLED true
set_interface_property external_signals EXPORT_OF ""
set_interface_property external_signals PORT_NAME_MAP ""
set_interface_property external_signals CMSIS_SVD_VARIABLES ""
set_interface_property external_signals SVD_ADDRESS_GROUP ""

add_interface_port external_signals enc_a enc_a Input 1
add_interface_port external_signals enc_b enc_b Input 1
add_interface_port external_signals leds leds Output 10
add_interface_port external_signals enc_sw enc_sw Input 1

